FROM debian:buster
RUN apt-get -qq update -qq
RUN apt-get -qq install -yq --no-install-suggests --no-install-recommends --force-yes ca-certificates libusb-1.0.0-dev cmake pkg-config libhidapi-dev git udev fuse file curl wget g++ make mesa-common-dev libglu1-mesa-dev libqt5core5a 	qtbase5-dev-tools 	qttools5-dev-tools qttools5-dev-tools libqt5svg5 qt5-default libqt5svg5-dev qttools5-dev-tools qttools5-dev xvfb rpm


